import pytest
from unittest.mock import AsyncMock, MagicMock
from app.services.explainable_service import ExplainableService
from app.models.llm import LLMResponse


@pytest.mark.asyncio
async def test_generate_explanation_success_json():
    # Mock LLM service
    mock_llm = AsyncMock()
    mock_llm.analyze.return_value = LLMResponse(
        analysis={"explanation": "This request is flagged as safe because it is a routine query."},
        provider="gemini",
        tokens_used=10,
        latency_ms=100
    )

    service = ExplainableService(llm_service_instance=mock_llm)
    context_data = {
        "llm_analysis": {"explanation": "Legacy fallback explanation"}
    }

    result = await service.generate_explanation(context_data)
    assert result == "This request is flagged as safe because it is a routine query."
    mock_llm.analyze.assert_called_once()


@pytest.mark.asyncio
async def test_generate_explanation_success_raw_text():
    # Mock LLM service returning string
    mock_llm = AsyncMock()
    mock_llm.analyze.return_value = LLMResponse(
        analysis="This is raw text generated by LLM.",
        provider="gemini",
        tokens_used=10,
        latency_ms=100
    )

    service = ExplainableService(llm_service_instance=mock_llm)
    context_data = {}

    result = await service.generate_explanation(context_data)
    assert result == "This is raw text generated by LLM."
    mock_llm.analyze.assert_called_once()


@pytest.mark.asyncio
async def test_generate_explanation_fallback_on_exception():
    # Mock LLM service throwing exception
    mock_llm = AsyncMock()
    mock_llm.analyze.side_effect = Exception("API quota exceeded")

    service = ExplainableService(llm_service_instance=mock_llm)
    context_data = {
        "llm_analysis": {"explanation": "Fallback analysis explanation"}
    }

    result = await service.generate_explanation(context_data)
    assert result == "Fallback analysis explanation"


@pytest.mark.asyncio
async def test_generate_explanation_fallback_default():
    # Mock LLM service throwing exception with empty context
    mock_llm = AsyncMock()
    mock_llm.analyze.side_effect = Exception("API quota exceeded")

    service = ExplainableService(llm_service_instance=mock_llm)
    result = await service.generate_explanation({})
    assert result == "Analysis completed."
